### ISSUE TITLE
Unable to serialize uint32

### ISSUE THREAD

**Issue by ArulselvanMadhavan** [dlozeve/bqn-npy#1]
Thanks for this work! I couldn't believe when I stumbled into this when I had all but given up and reluctantly started thinking about writing a serialization library. 

However the test fail for unsigned integer types with error "Unsupported bit width 32 for uint". I'm on a RHEL8 OS on a x86 processor

**Comment by dlozeve** [comment]
Hello, thanks for the report! I have attempted to circumvent this, this seems to be an issue with how CBQN handles unsigned integers. I'm not sure if something changed in CBQN leading to this test failure...

More details in the commit message: https://github.com/dlozeve/bqn-npy/commit/9a1d25171690df1e83e3c8eb7187f6fc9a7d9698
